name: Node.js CI

on:
  push:
    branches:
      - unit-test
  pull_request:
    branches:
      - unit-test

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x] # Versi Node.js yang akan diuji

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test
